# Generated by Django 3.0.5 on 2021-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('transition', models.IntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('closing_link', models.TextField(max_length=75)),
            ],
        ),
    ]
