# Generated by Django 3.0.5 on 2021-05-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ab_service', '0002_auto_20210530_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
