# Generated by Django 3.0.5 on 2021-05-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ab_service', '0004_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
