# Generated by Django 3.0.5 on 2021-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ab_service', '0005_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('views', models.IntegerField(default=0)),
                ('transition', models.IntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('closing_link', models.CharField(max_length=75)),
            ],
        ),
    ]
