# Generated by Django 3.0.5 on 2021-05-30 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ab_service', '0008_prealand'),
    ]

    operations = [
        migrations.AddField(
            model_name='prealand',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
