# Generated by Django 3.2.4 on 2021-07-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prealand',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
