# Generated by Django 3.0.5 on 2021-05-30 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ab_service', '0006_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
