# Generated by Django 3.0.5 on 2021-05-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ab_service', '0007_auto_20210530_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prealand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('link', models.CharField(max_length=75)),
                ('uniqueness', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('transition', models.IntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ab_service.Offer')),
            ],
        ),
    ]
