# Generated by Django 3.2.4 on 2021-07-01 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('views', models.IntegerField(default=0)),
                ('transition', models.IntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_link', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Prealand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('link', models.CharField(max_length=75)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uniqueness', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('transition', models.IntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abservice.offer')),
            ],
        ),
    ]
